import { expect, test } from "bun:test";
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { spawnToolSync, toolInvocation } from "./tool-invocation-lib.mjs";
import { inspectDeveloperToolUpdates, DEVELOPER_TOOL_DEFINITIONS } from "./tool-update-lib.mjs";

// Generated by npm's cmd-shim, not by the parser under test.
const template = readFileSync(new URL("../testdata/tool-invocation/npm-codex.cmd", import.meta.url), "utf8");
function fixture() {
  const root = mkdtempSync(join(tmpdir(), "lazurio npm & % ! "));
  const packageRoot = join(root, "node_modules", "@openai", "codex");
  mkdirSync(join(packageRoot, "bin"), { recursive: true });
  const entry = join(packageRoot, "bin", "codex.js"), shim = join(root, "codex.cmd");
  writeFileSync(shim, template);
  writeFileSync(join(packageRoot, "package.json"), JSON.stringify({ name: "@openai/codex", bin: { codex: "bin/codex.js" } }));
  writeFileSync(entry, 'console.log(process.argv[2] === "--version" ? "codex-cli 0.153.3" : JSON.stringify(process.argv.slice(2)))');
  if (process.platform === "win32") copyFileSync(Bun.which("node"), join(root, "node.exe"));
  else symlinkSync(Bun.which("node"), join(root, "node.exe"));
  return { root, entry, shim, packageRoot };
}

test("npm shim maps to its declared JS bin and sibling Node without shell interpolation", () => {
  const f = fixture();
  try {
    const args = ['space here', 'a&b', '%PATH%', '!value!', '"quoted"', 'trailing\\'];
    const plan = toolInvocation(f.shim, args, { platform: "win32", environment: { PATH: "unavailable" } });
    expect(plan).toEqual({ executable: join(f.root, "node.exe"), args: [f.entry, ...args] });
    const result = spawnSync(plan.executable, plan.args, { encoding: "utf8", shell: false });
    expect(result.status, result.stderr).toBe(0);
    expect(JSON.parse(result.stdout)).toEqual(args);
    expect(toolInvocation("C:\\custom\\native.exe", args, { platform: "win32" })).toEqual({ executable: "C:\\custom\\native.exe", args });
  } finally { rmSync(f.root, { recursive: true, force: true }); }
});

test("npm Node fallback follows PATH; altered scripts and mismatched package bins fail closed", () => {
  const f = fixture();
  try {
    const nodeDirectory = join(f.root, "Node from PATH"); mkdirSync(nodeDirectory);
    copyFileSync(join(f.root, "node.exe"), join(nodeDirectory, "node.exe"));
    rmSync(join(f.root, "node.exe"));
    expect(toolInvocation(f.shim, [], { platform: "win32", environment: { Path: nodeDirectory, PATHEXT: ".EXE" } }).executable).toBe(join(nodeDirectory, "node.exe"));
    writeFileSync(f.shim, `echo unexpected\r\n${template}`);
    expect(() => toolInvocation(f.shim, [], { platform: "win32" })).toThrow("Unsupported Windows script shim");
    writeFileSync(f.shim, template);
    writeFileSync(join(f.packageRoot, "package.json"), JSON.stringify({ bin: { codex: "other.js" } }));
    expect(() => toolInvocation(f.shim, [], { platform: "win32" })).toThrow("Unsupported Windows script shim");
  } finally { rmSync(f.root, { recursive: true, force: true }); }
});

test.skipIf(process.platform !== "win32")("native Windows tool update consumer runs a real npm-generated codex.cmd", async () => {
  const f = fixture(), originalPath = process.env.PATH;
  try {
    process.env.PATH = f.root;
    const result = spawnToolSync(f.shim, ["--version"], { encoding: "utf8" });
    expect(result.status, result.stderr).toBe(0);
    expect(result.stdout.trim()).toBe("codex-cli 0.153.3");
    const checks = await inspectDeveloperToolUpdates({
      definitions: DEVELOPER_TOOL_DEFINITIONS.filter((definition) => definition.id === "codex"),
      fetchRelease: async () => ({ version: "0.153.3", url: "https://example.invalid/release" }),
    });
    expect(checks[0].current_version).toBe("0.153.3");
    expect(checks[0].status).not.toBe("probe_failed");
  } finally {
    if (originalPath === undefined) delete process.env.PATH; else process.env.PATH = originalPath;
    rmSync(f.root, { recursive: true, force: true });
  }
});
